[package]
name = "bw_content"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Data schemas, content database, and generator registries"

[dependencies]
bw_core.workspace = true
serde.workspace = true
ron.workspace = true
thiserror.workspace = true
smol_str.workspace = true
indexmap.workspace = true
rand_chacha.workspace = true
rand.workspace = true
