//! A cohesive-aggregate soil simulation, on a world-anchored tile grid.
//!
//! ## Why noise cannot do this, however it is shaped
//!
//! Three shapes were tried on top of a value-noise field before this: a fold, a
//! power skew, and a two-level fracture with steep walls. Each fixed a real
//! defect — worms, a surface too flat to cast a shadow, spheres on a plane — and
//! none of them fixed the thing that made a render of bare earth read as a
//! nineties video game, because that thing is not a property of the shaping
//! function.
//!
//! **Procedural noise is statistically uniform.** Every patch of it has the same
//! distribution as every other patch. That is what the word "noise" means and it
//! is why a square metre of it reads as one texture tiled, however well the
//! texture is tuned and however many bands are stacked.
//!
//! Real ground is not like that, and the reason is not that it is more detailed.
//! It is that it *has a history*. Material fell here and was pushed there. This
//! clod slumped against that one and stopped. Water ran down this line and took
//! the loose grains with it, leaving the packed ones. A hoof went in here, threw
//! a rim up around itself, and the rim has been drying ever since. Every feature
//! on a real soil surface is the trace of an event, and the events are causally
//! linked — which is exactly the structure a field of independent samples cannot
//! have.
//!
//! So this simulates the events instead of describing their outcome.
//!
//! ## What is simulated, and at what scale
//!
//! Not grains. A full granular treatment — DEM, SPH, MPM — reproduces transport
//! and clogging and phase change, and needs particle counts and time steps that
//! are absurd when the answer wanted is a static surface.
//!
//! The particle here is a **mesoscopic aggregate**: a clod, a lump, a packet of
//! soil holding many grains together. That is the scale at which soil actually
//! behaves as a distinct object, it is the scale the reference photograph is
//! mostly made of, and a few thousand of them is enough.
//!
//! Four fields on a height grid:
//!
//! ```text
//! base       the ground the soil is lying on
//! soil       how much movable material is here
//! moisture   how wet it is, 0..1
//! strength   how well the aggregates here hold together, 0..1
//! ```
//!
//! and four stages over them, which is the whole model:
//!
//! 1. **Deposit** irregular multi-lobed aggregate packets.
//! 2. **Slump** toward a moisture-dependent angle of repose, and stop early.
//! 3. **Disturb** — pits and prints, with their spoil thrown around the rim.
//! 4. **Wash** — short downhill paths that lift loose material and drop it in
//!    hollows.
//!
//! Everything finer than a cell stays where it was: in the shader's relief
//! bands, as a bump, and below that in the roughness.
//!
//! ## The part that makes it usable here
//!
//! Sampling in this framework must be a pure function of world position. Two
//! overlapping windows over the same ground have to agree exactly, or a plate
//! traced in slices grows seams. A simulation is the opposite of that: a grid,
//! iterated, where every cell depends on its neighbours.
//!
//! The reconciliation is three rules.
//!
//! **The grid is anchored to the world, not to the window.** Tile indices come
//! from dividing world coordinates, so the same ground always lands in the same
//! tile at the same offset within it.
//!
//! **Every event is seeded from a world cell, not from a sequence.** Packets,
//! disturbances and wash paths are all generated by hashing a coarse world cell,
//! so a packet straddling a tile boundary is generated identically by both
//! tiles. Nothing is drawn from a running stream, because a running stream
//! depends on how many draws came before it and therefore on where the window
//! started.
//!
//! **Each tile is simulated with a halo and only its interior is kept.** Slump
//! transport is diffusive rather than ballistic — over `n` passes material
//! spreads about `sqrt(n * rate)` cells, not `n` — and wash paths are explicitly
//! capped. [`HALO_CELLS`] is set well past both bounds, and a test simulates the
//! same ground at two halo widths and asserts the interiors match.

use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use glam::Vec2;
use terrain_core::ground_material::GroundMaterialProfile;

use crate::rng::{Draw, Stream, fbm};

/// How far a tile reaches beyond itself before its interior can be trusted.
///
/// Sized against the two transport mechanisms rather than guessed. Slumping is
/// diffusive: [`SLUMP_PASSES`] passes at [`SLUMP_RATE`] spread material about
/// `sqrt(passes * rate)` cells, which is under ten. Wash paths are ballistic but
/// capped at [`WASH_STEPS`] steps of one cell. Twice the sum, rounded up.
const HALO_CELLS: usize = 96;

/// Metres along one simulated tile's edge.
///
/// ## Larger than the obvious metre, because the halo is not free
///
/// The halo is a fixed number of *cells*, so it costs the same whatever the tile
/// is. At a metre with a sixty-four cell halo, a tile was 125 cells of interior
/// inside 253 cells of grid — three quarters of the work thrown away. At two
/// metres the same halo wraps 250 cells and the waste falls by half.
///
/// The ceiling on it is that a tile takes one value for the state fields it
/// simulates under, sampled at its centre. Two metres is about as far as a
/// meadow's moisture and compaction can be treated as constant before that
/// starts showing as a step at a tile boundary.
const TILE_M: f32 = 2.0;

/// How many relaxation passes, and how much of the excess each one moves.
///
/// ## Deliberately stopped early
///
/// A fully relaxed heightfield is at its angle of repose everywhere, which is a
/// smooth conical surface and reads as poured sand. Real ground is caught at
/// every stage of settling at once: a clod that has stood since it was thrown, a
/// face that collapsed yesterday, a rim still holding. Stopping short is what
/// keeps that mixture, and it is a feature rather than a budget.
const SLUMP_PASSES: usize = 150;
const SLUMP_RATE: f32 = 0.35;

/// How far a wash path may travel, in cells. Bounds the halo — see [`HALO_CELLS`].
const WASH_STEPS: usize = 30;

/// Above this wavelength a band is landform rather than aggregate: the swell of
/// the ground, not a lump lying on it.
///
/// Bands above it become the bed this simulation runs over; bands below it are
/// what the events themselves produce, and drawing both would double-count.
const LANDFORM_M: f32 = 0.09;

/// The coarse world grid that events are seeded from.
///
/// Every packet, pit and wash path is drawn from a cell of this grid, so the
/// same event is generated identically by every tile whose halo covers it. That
/// is the whole seam guarantee — see this module's docs.
const EVENT_CELL_M: f32 = 0.125;

/// One tile of simulated ground, ready to sample.
pub struct SoilTile {
    /// Interior only. Relief above the soil's datum, in metres.
    height: Vec<f32>,
    /// Samples along one edge — one more than the cell count, so a tile shares
    /// its boundary row with its neighbour. See [`Grid::into_interior`].
    side: usize,
}

impl SoilTile {
    /// Bilinear, in cell coordinates within the interior.
    fn sample(&self, x: f32, y: f32) -> f32 {
        let last = self.side - 1;
        let x = x.clamp(0.0, last as f32);
        let y = y.clamp(0.0, last as f32);
        let (x0, y0) = (x.floor() as usize, y.floor() as usize);
        let (x1, y1) = ((x0 + 1).min(last), (y0 + 1).min(last));
        let (fx, fy) = (x - x0 as f32, y - y0 as f32);
        let at = |cx: usize, cy: usize| self.height[cy * self.side + cx];
        let top = at(x0, y0) + (at(x1, y0) - at(x0, y0)) * fx;
        let bottom = at(x0, y1) + (at(x1, y1) - at(x0, y1)) * fx;
        top + (bottom - top) * fy
    }
}

/// The simulated surface for one soil, tiled across the world and cached.
pub struct SoilSurface {
    seed: u64,
    profile: Arc<GroundMaterialProfile>,
    cell_m: f32,
    cells: usize,
    /// Simulating a tile costs milliseconds and a plate asks for each one
    /// hundreds of thousands of times, so they are kept. Keyed by tile index,
    /// which is a pure function of world position.
    tiles: Mutex<HashMap<((i32, i32), u8, u8), Arc<SoilTile>>>,
}

impl SoilSurface {
    /// Prepare a surface for `profile`, resolving to `cell_m`.
    ///
    /// The cell size comes from the profile's declared mesh floor: the soil says
    /// how fine a structure it wants carried as geometry, and that is exactly
    /// the scale below which this simulation has nothing to say and the shader's
    /// bands take over.
    pub fn new(profile: Arc<GroundMaterialProfile>, seed: u64) -> Self {
        let floor = profile
            .structure
            .mesh_floor_m
            .or_else(|| profile.coarsest_band().map(|b| b.wavelength_m))
            .unwrap_or(0.02)
            .clamp(0.004, 0.06);
        // Two cells across the finest structure asked for, which is what it
        // takes to have a shape at all.
        let cells = (TILE_M / (floor * 0.5)).round().clamp(32.0, 512.0) as usize;
        Self {
            seed,
            profile,
            cell_m: TILE_M / cells as f32,
            cells,
            tiles: Mutex::new(HashMap::new()),
        }
    }

    /// The simulated relief at a world point, in metres. Zero-mean over a tile.
    pub fn height(&self, world: Vec2, moisture: f32, compaction: f32) -> f32 {
        // A soil that declares no relief has none, and must not be given any by
        // this module's own defaults — see `Params::of`.
        if self.profile.structure.bands.is_empty() {
            return 0.0;
        }
        let tile = (
            (world.x / TILE_M).floor() as i32,
            (world.y / TILE_M).floor() as i32,
        );
        let built = self.tile(tile, moisture, compaction);
        let local = Vec2::new(
            world.x - tile_origin(tile.0),
            world.y - tile_origin(tile.1),
        );
        built.sample(local.x / self.cell_m, local.y / self.cell_m)
    }

    fn tile(&self, index: (i32, i32), moisture: f32, compaction: f32) -> Arc<SoilTile> {
        // ## The state is part of the key, and for a while only the comment
        // said so
        //
        // A tile is simulated *under* a moisture and a compaction — they set
        // the cohesion, the depth of the movable layer and how readily the
        // ground marks — so two tiles at the same place in different states are
        // two different answers. Keyed on the index alone, the first state to
        // reach a tile won and every later sample got its surface: a damp hollow
        // and the dry crown beside it returned the same ground, and which one
        // depended on the order the sampler happened to walk in.
        //
        // Quantised, because the state varies continuously and an exact key
        // would make every sample a miss. Sixteen levels puts the step between
        // two of them well under the noise the surface already carries, and
        // makes the answer independent of sampling order — which is the property
        // the whole tiling scheme rests on.
        let level = |v: f32| (v.clamp(0.0, 1.0) * 15.0).round() as u8;
        let key = (index, level(moisture), level(compaction));
        if let Some(found) = self.tiles.lock().expect("soil cache").get(&key) {
            return Arc::clone(found);
        }
        let built = Arc::new(self.simulate(
            index,
            level(moisture) as f32 / 15.0,
            level(compaction) as f32 / 15.0,
            HALO_CELLS,
        ));
        self.tiles
            .lock()
            .expect("soil cache")
            .insert(key, Arc::clone(&built));
        built
    }

    /// Run the four stages over one tile plus `halo`, and keep the interior.
    fn simulate(
        &self,
        index: (i32, i32),
        moisture: f32,
        compaction: f32,
        halo: usize,
    ) -> SoilTile {
        let mut grid = Grid::new(self.cells, halo, self.cell_m, index);
        let params = Params::of(&self.profile, moisture, compaction);

        // Order matters, and it is the order the events happened in. Ground was
        // laid down and settled; then things were pressed into it; then water
        // ran over the result. Disturbing before the main relaxation — which the
        // first version did — slumps every print away again, and a surface with
        // no prints on it is most of the way back to being noise.
        deposit(&mut grid, &params, self.seed, &self.profile);
        slump(&mut grid, &params);
        disturb(&mut grid, &params, self.seed);
        wash(&mut grid, &params, self.seed);
        // A short second relaxation, so the wash's spoil and the disturbance
        // rims settle against what is already there rather than sitting on it.
        slump_passes(&mut grid, &params, SLUMP_PASSES / 5);

        grid.into_interior(params.depth_m)
    }
}

fn tile_origin(index: i32) -> f32 {
    index as f32 * TILE_M
}

/// The simulation's constants, derived from an authored profile and a state.
///
/// Nothing here is a literal chosen in this file. The soil says how cohesive it
/// is, how large its aggregates are and how it responds to being packed and
/// soaked; this turns those into the numbers the stages need, so retuning a
/// material stays a matter of editing its `.ground.ron`.
struct Params {
    /// Metres of movable soil laid down, before anything moves it.
    depth_m: f32,
    /// Packet radii, from the profile's own aggregate scales.
    packet_min_m: f32,
    packet_max_m: f32,
    packets_per_m2: f32,
    /// `tan(phi)` — the dry angle of repose as a slope.
    friction: f32,
    /// How much cohesion the damp state adds, as an extra slope.
    cohesion: f32,
    /// How much of the excess slope a saturated soil gives back.
    fluidity: f32,
    disturbances_per_m2: f32,
    disturbance_depth_m: f32,
    wash_per_m2: f32,
    wash_strength: f32,
}

impl Params {
    fn of(profile: &GroundMaterialProfile, moisture: f32, compaction: f32) -> Self {
        let moisture = moisture.clamp(0.0, 1.0);
        let compaction = compaction.clamp(0.0, 1.0);
        let bands = &profile.structure.bands;
        let coarse = bands.first().map(|b| b.wavelength_m).unwrap_or(0.06);
        // ## No fallback amplitude
        //
        // This defaulted to two centimetres when a profile declared no bands,
        // which meant a material stating it had **no relief** got forty-four
        // millimetres of soil laid down and then pitted. The laboratory's flat
        // control card measured 1.57 mm of roughness, and since every other
        // figure in that suite is compared against the control, all of them were
        // inflated by it.
        //
        // A soil that declares no structure has none. The defaults above are for
        // *scales*, which only matter if there is something to scale.
        let coarse_amp = bands.first().map(|b| b.amplitude_m).unwrap_or(0.0);
        // The aggregate band: the coarsest thing this soil declares that is
        // still a lump rather than a landform.
        let aggregate = bands
            .iter()
            .find(|b| b.wavelength_m <= 0.09)
            .map(|b| b.wavelength_m)
            .unwrap_or(coarse * 0.4);

        // ## Cohesion peaks damp, not wet
        //
        // Liquid bridges between grains are what hold a clod together, and they
        // need water to exist and are destroyed by enough of it: a damp soil
        // stands in steeper faces than either a dry or a soaked one. The curve
        // is the standard single-peak shape — rising linearly, falling
        // exponentially — normalised to one at its peak.
        let peak = 0.38;
        let ratio = moisture / peak;
        let damp = ratio * (1.0 - ratio).exp();
        let cohesion = profile.structure.cohesion.clamp(0.0, 1.0);

        Self {
            // Enough that the aggregates have something to slump into. Less on
            // a packed track, which is what packed means.
            depth_m: coarse_amp * 2.2 * (1.0 - 0.35 * compaction),
            packet_min_m: aggregate * 0.55,
            packet_max_m: aggregate * 1.9,
            // ## Occasional, not a pavement
            //
            // The first figure here was `2.2 / aggregate^2` — six hundred
            // packets a square metre, overlapping three deep — on the reasoning
            // that the surface should be *made* of aggregates rather than dotted
            // with them. What that renders is a bed of blobs, which is the same
            // picture the dome shape gave and was rejected for: pebbles, evenly
            // sized, evenly spread, each with a highlight on it.
            //
            // Looking again at the reference photograph, that reading is simply
            // wrong about soil. Most of that surface is a fairly even bed. What
            // makes it read as earth is not the lumps standing on it — those are
            // occasional — it is that the bed is **pitted**: voids, pores and
            // small collapses, which is negative relief. So the packets thin out
            // by a factor of five and `disturb` takes over the texture.
            // ## Rare, and large enough to be seen
            //
            // Six hundred a square metre was a pavement of pebbles. Thinning
            // them to a hundred and twenty removed the pavement and removed the
            // clods with it — the surface came back as an even fine grain with
            // no aggregate anywhere, which is the other failure and just as
            // wrong.
            //
            // A clod in the reference is a *distinct object*: it is read because
            // it is bigger than the grain around it and because there is quiet
            // bed either side. So there are few of them and they are large,
            // rather than many and middling. Thirty-five a square metre puts one
            // every seventeen centimetres, which is about what the photograph
            // shows.
            packets_per_m2: 0.125 / (aggregate * aggregate),
            // A loose soil stands near 33 degrees, a cohesive one steeper.
            friction: 0.62 + 0.30 * cohesion,
            cohesion: 1.5 * cohesion * damp,
            // Saturated ground runs. Below the peak this is nothing at all,
            // which is what keeps damp soil cloddy.
            fluidity: smoothstep(0.68, 1.0, moisture).powi(2),
            // ## Where the texture actually comes from
            //
            // Ninety a square metre was a scattering of prints on an otherwise
            // smooth bed. It is now the stage that carries the surface, because
            // the reference's texture is overwhelmingly *negative* — the eye
            // reads soil from its holes, not from its bumps, and a bed of bumps
            // reads as gravel however carefully the bumps are shaped.
            // ## Packed ground takes fewer marks, and shallower ones
            //
            // Both of these rose with compaction, on the reasoning that a worn
            // surface has been stood on more often. That confuses a cause with
            // its effect: compaction is *what traffic already did*, and the
            // question here is what the ground does next. Packed ground resists
            // — fewer marks and shallower — which is why an old path holds its
            // shape while a freshly turned bed does not.
            //
            // With both rising it did not flatten at all. Measured on the
            // laboratory's own card, compacted ground came back at 0.00175
            // against loose ground's 0.00089: twice as rough, from the material
            // that declares itself pressed flat, and the profile's per-band
            // `compaction_response` saying the opposite the whole time.
            disturbances_per_m2: 260.0 - 110.0 * compaction,
            disturbance_depth_m: coarse_amp * (1.0 - 0.55 * compaction),
            wash_per_m2: 900.0,
            // Water only moves material it can lift, and a packed damp soil
            // resists. This is what puts streaks on a wet slope and nothing on
            // a dry crust.
            wash_strength: 0.35 * (0.25 + 0.75 * moisture) * (1.0 - 0.5 * compaction),
        }
    }
}

/// The four fields, over a tile and its halo.
struct Grid {
    /// Interior width in cells; the stored grid is this plus twice the halo.
    cells: usize,
    halo: usize,
    width: usize,
    cell_m: f32,
    /// World position of the *tile's* `(0, 0)` cell — not the stored grid's.
    ///
    /// ## Why the tile's corner and not the grid's
    ///
    /// The obvious anchor is the grid's own origin, `tile - halo * cell`. It is
    /// also the one that makes a tile's contents depend on its halo width, for a
    /// reason that took a while to find and is worth writing down: with a
    /// different halo the same world point is reached by a *different sum*, so it
    /// lands a unit in the last place away. Ordinarily that is nothing. Here the
    /// slump has a threshold in it — material moves or it does not — so a
    /// last-place difference flips a branch, and a hundred and eighty passes
    /// amplify the flip into three quarters of a millimetre.
    ///
    /// Anchoring to the tile instead makes every world coordinate a function of
    /// the tile index and the cell offset alone. Two runs at different halo
    /// widths then agree bit for bit, and so do two neighbouring tiles about the
    /// ground they share.
    origin: Vec2,
    /// Cells of halo, so a stored index can be turned back into a tile offset.
    origin_cells: i32,
    soil: Vec<f32>,
    strength: Vec<f32>,
}

impl Grid {
    fn new(cells: usize, halo: usize, cell_m: f32, index: (i32, i32)) -> Self {
        let width = cells + 2 * halo;
        Self {
            cells,
            halo,
            width,
            cell_m,
            origin: Vec2::new(tile_origin(index.0), tile_origin(index.1)),
            origin_cells: halo as i32,
            soil: vec![0.0; width * width],
            strength: vec![0.0; width * width],
        }
    }

    #[inline]
    fn at(&self, x: usize, y: usize) -> usize {
        y * self.width + x
    }

    /// The world point a stored cell centre sits at.
    #[inline]
    fn world_of(&self, x: usize, y: usize) -> Vec2 {
        self.world_of_unclamped(x as i32, y as i32)
    }

    /// The same, for cell indices that may lie outside the stored grid.
    ///
    /// Kernels are summed over their whole footprint and written only where the
    /// grid holds it — see `splat` — so they have to be able to ask about ground
    /// this tile is not storing.
    #[inline]
    fn world_of_unclamped(&self, x: i32, y: i32) -> Vec2 {
        self.origin
            + Vec2::new(
                (x - self.origin_cells) as f32,
                (y - self.origin_cells) as f32,
            ) * self.cell_m
    }

    /// Cell coordinates of a world point, unclamped, in stored-grid space.
    #[inline]
    fn cell_of(&self, world: Vec2) -> Vec2 {
        (world - self.origin) / self.cell_m + Vec2::splat(self.origin_cells as f32)
    }

    /// Drop the halo, and take the datum off.
    ///
    /// ## The datum is a constant, not this tile's own mean
    ///
    /// Subtracting each tile's mean is the obvious way to keep the simulation
    /// from raising the ground it sits on, and it puts a **step at every tile
    /// join**: two neighbours with different mean depths get different offsets,
    /// so a continuous surface is cut into squares that do not line up. Measured
    /// on the first run, the join moved by seventeen millimetres — larger than
    /// most of the relief either side of it.
    ///
    /// The deposit stage lays down a known constant depth and every stage after
    /// it conserves material, so that constant *is* the datum, and taking it off
    /// is both what keeps the mean near zero and what keeps tiles agreeing.
    fn into_interior(self, datum: f32) -> SoilTile {
        // ## `cells + 1` samples, not `cells`
        //
        // A tile covering one metre at a cell size of `s` needs samples at
        // `0, s, .. 1` inclusive — one more than the number of cells — so that
        // its **last sample and its neighbour's first are the same world point**.
        // Storing `cells` of them instead leaves a cell-wide gap between tiles
        // that the bilinear read has to invent, and the join stepped by
        // seventeen millimetres because of it.
        let side = self.cells + 1;
        let mut height = Vec::with_capacity(side * side);
        for y in 0..side {
            for x in 0..side {
                height.push(self.soil[self.at(x + self.halo, y + self.halo)] - datum);
            }
        }
        SoilTile {
            height,
            side,
        }
    }
}

/// Stage one: lay down irregular aggregate packets.
///
/// ## Why a packet is not a Gaussian
///
/// A circular bump is the shape nothing in soil has. A clod is an accretion of
/// smaller lumps that stuck together, with a lopsided outline, a flat where it
/// came to rest and a shoulder where the next one leans on it. So each packet is
/// the sum of three to nine offset lobes of differing radius, which produces
/// that outline for the cost of a few more exponentials and without any
/// collision detection at all.
fn deposit(grid: &mut Grid, params: &Params, seed: u64, profile: &GroundMaterialProfile) {
    // ## The bed is not flat before anything lands on it
    //
    // The first version started from a constant depth and let events do
    // everything. What that produced was a surface with a great deal of texture
    // at event scale — four to ten centimetres — and **nothing above it**: an
    // even sheet of fine pitting, which reads as coarse sandpaper rather than as
    // ground.
    //
    // The reference photograph keeps more than half its variance between nine
    // and thirty-five centimetres. That is the swell of the ground itself: where
    // it was heaped, where it settled, where it drains. Nothing at event scale
    // can supply it, and it has to be there before the events land or they sit
    // on a plane.
    //
    // It comes from the profile's own coarse bands — the ones above aggregate
    // scale, which describe landform rather than lumps — so the soil still says
    // what shape it is, and this stage says what happened to it.
    for y in 0..grid.width {
        for x in 0..grid.width {
            let world = grid.world_of(x, y);
            let mut swell = 0.0;
            for (index, band) in profile.structure.bands.iter().enumerate() {
                if band.wavelength_m < LANDFORM_M {
                    continue;
                }
                swell += broad_band(band, index, world, seed);
            }
            let index = grid.at(x, y);
            grid.soil[index] = params.depth_m + swell;
        }
    }

    let margin = params.packet_max_m * 2.4;
    for_each_event(grid, seed, Stream::Soil, params.packets_per_m2, margin, 0.30, |draw, at, grid| {
        let mut draw = draw;
        // Log-normal-ish: small packets common, large clods rare, which is what
        // a sieve of real soil measures.
        let roll = draw.unit();
        let radius = params.packet_min_m
            * (params.packet_max_m / params.packet_min_m).powf(roll * roll * roll);
        let mass = params.depth_m * 0.55 * draw.range(0.5, 1.6);

        let lobes = 3 + draw.index(7);
        let mut offsets = [(Vec2::ZERO, 0.0f32); 9];
        for lobe in offsets.iter_mut().take(lobes) {
            let angle = draw.range(0.0, std::f32::consts::TAU);
            let reach = draw.range(0.0, 0.85) * radius;
            *lobe = (
                Vec2::new(angle.cos(), angle.sin()) * reach,
                radius * draw.range(0.45, 1.0),
            );
        }

        splat(grid, at, radius * 2.2, |world| {
            let mut sum = 0.0;
            for (offset, lobe_radius) in offsets.iter().take(lobes) {
                let d = (world - at - *offset).length_squared();
                sum += (-d / (2.0 * lobe_radius * lobe_radius)).exp();
            }
            sum
        }, mass, draw.range(0.35, 1.0));
    });
}

/// Add a normalised kernel's worth of `mass` around `at`, and the strength with
/// it. The kernel is evaluated at cell centres and divided by its own sum, so
/// the mass laid down is the mass asked for whatever shape it has.
fn splat(
    grid: &mut Grid,
    at: Vec2,
    reach_m: f32,
    kernel: impl Fn(Vec2) -> f32,
    mass: f32,
    strength: f32,
) {
    let centre = grid.cell_of(at);
    let reach = (reach_m / grid.cell_m).ceil() as i32;
    let (cx, cy) = (centre.x.round() as i32, centre.y.round() as i32);
    let width = grid.width as i32;

    // ## The normalisation runs over the whole footprint, clipped or not
    //
    // Dividing by the sum of only the cells that happen to lie inside the grid
    // makes a packet's mass depend on where the grid's edge is. One straddling a
    // boundary gets its mass divided by a smaller total and lands heavier than
    // the same packet drawn a metre away — so a tile's answer depended on its own
    // halo width, and doubling the halo moved cells by three quarters of a
    // millimetre out to a hundred and thirty cells in.
    //
    // So the kernel is summed everywhere it reaches and written only where it
    // can be. What falls outside is material that left the tile, which is
    // correct: it did.
    let mut total = 0.0;
    let mut touched: Vec<(usize, f32)> = Vec::new();
    for y in (cy - reach)..=(cy + reach) {
        for x in (cx - reach)..=(cx + reach) {
            let value = kernel(grid.world_of_unclamped(x, y));
            if value <= 1.0e-4 {
                continue;
            }
            total += value;
            if x >= 0 && y >= 0 && x < width && y < width {
                touched.push((grid.at(x as usize, y as usize), value));
            }
        }
    }
    if total <= 0.0 {
        return;
    }
    for (index, value) in touched {
        let share = value / total;
        grid.soil[index] += mass * share;
        // Strength is a maximum rather than a sum: a cell is as strong as the
        // strongest thing holding it, and adding would drive every overlap to
        // one and remove the variation this exists to provide.
        let here = strength * (value / total * touched_scale(total));
        if here > grid.strength[index] {
            grid.strength[index] = here.min(1.0);
        }
    }
}

/// Normalising a kernel by its own sum makes the per-cell share tiny for a wide
/// packet, which would make strength depend on radius rather than on the soil.
/// This puts it back on the same footing whatever the packet's size.
#[inline]
fn touched_scale(total: f32) -> f32 {
    total.max(1.0)
}

/// Stage two: relax toward a moisture-dependent angle of repose, and stop short.
fn slump(grid: &mut Grid, params: &Params) {
    slump_passes(grid, params, SLUMP_PASSES);
}

fn slump_passes(grid: &mut Grid, params: &Params, passes: usize) {
    let inv = 1.0 / grid.cell_m;
    for pass in 0..passes {
        // Checkerboard, so the answer does not depend on which way the loop
        // happens to run. Sweeping in raster order drags material south-east
        // over enough passes and puts a visible grain on the whole surface.
        let parity = pass & 1;
        for y in 1..grid.width - 1 {
            for x in 1..grid.width - 1 {
                if (x + y) & 1 != parity {
                    continue;
                }
                let here = grid.at(x, y);
                let height = grid.soil[here];
                if height <= 0.0 {
                    continue;
                }

                // Steepest descent among the four neighbours.
                let mut lowest = here;
                let mut drop = 0.0;
                for (nx, ny) in [(x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)] {
                    let there = grid.at(nx, ny);
                    let difference = height - grid.soil[there];
                    if difference > drop {
                        drop = difference;
                        lowest = there;
                    }
                }
                if lowest == here {
                    continue;
                }

                let slope = drop * inv;
                // ## Shallow clods stand where deep piles cannot
                //
                // Cohesion is a *force* and the load it has to hold is
                // proportional to the depth of material above it, so dividing by
                // that depth is not a fudge — it is what makes a two-centimetre
                // clod keep a near-vertical side while a hand-deep heap of the
                // same soil slumps flat. It is most of what separates soil from
                // sand in a picture.
                let critical = params.friction
                    + params.cohesion * (1.0 + grid.strength[here])
                        / height.max(grid.cell_m);
                if slope <= critical {
                    continue;
                }

                let excess = slope - critical;
                let moved = (SLUMP_RATE * excess * grid.cell_m
                    * (1.0 + 3.0 * params.fluidity))
                    .min(drop * 0.5)
                    .min(height);
                grid.soil[here] -= moved;
                grid.soil[lowest] += moved;

                // Shearing breaks the bonds it slides across, and the material
                // that arrives is loose. Without this every surface ends up
                // uniformly strong and the second slump does nothing.
                grid.strength[here] = (grid.strength[here] - 0.35 * moved * inv).max(0.0);
                grid.strength[lowest] =
                    (grid.strength[lowest] - 0.15 * moved * inv).max(0.0);
            }
        }
    }
}

/// Stage three: pits, prints and scuffs, with their spoil thrown around them.
///
/// The dark holes in a photograph of soil are not noise minima. Something made
/// them, and the something also threw material out: a hollow with no rim reads
/// as a dent in a sheet, which is what an unadorned negative bump looks like.
fn disturb(grid: &mut Grid, params: &Params, seed: u64) {
    for_each_event(
        grid,
        seed,
        Stream::Dirt,
        params.disturbances_per_m2,
        // The widest disturbance is a broad pressed patch: 13 cm across, up to
        // twice as long once it is squashed and turned, and its rim reaches
        // nearly twice that again.
        0.9,
        // Down to a sixth in the quiet stretches. This is the term that decides
        // whether a plate of soil reads as one texture or as ground.
        0.16,
        |draw, at, grid| {
            let mut draw = draw;
            // Three classes, so the surface is not covered in one size of hole:
            // many small pits, fewer medium hollows, the occasional broad
            // pressed patch. The broad ones are shallow, or the ground turns
            // into craters.
            // ## Sized against what the picture can resolve
            //
            // The first pass put eighty per cent of these between four and
            // thirteen millimetres, on the reasoning that soil's texture is
            // fine. It is — but at this project's trace resolution four
            // millimetres is **a pixel and a bit**, so what rendered was not
            // fine texture, it was aliasing: a uniform pale speckle that read as
            // coarse sandpaper.
            //
            // The reference's texture is resolved because the photograph is
            // taken at four times the sampling rate. At ours, the band that can
            // actually be seen as *shape* is two to five centimetres, and
            // anything below that belongs to the shader's bump and then to its
            // roughness — which is exactly the three-tier split the rest of this
            // pipeline already draws, applied to the simulation.
            // ## One event that is not round
            //
            // Every event in this simulation was radially symmetric — round
            // pits, round packets — so however they were tuned the interior of a
            // worked region came out as isotropic stipple. What a track actually
            // carries is *directional*: ruts, smears, compacted shelves, all
            // running the way the traffic went, and all of them long compared to
            // their width.
            //
            // A rut is the same footprint machinery at a much higher squash and
            // with its turn pinned tightly to the shared travel bias instead of
            // jittered away from it. Long, shallow, aligned, and compacting what
            // is left in the bottom — which is what a rut is.
            let roll = draw.unit();
            let is_rut = roll >= 0.985;
            let (radius, depth, rim) = if is_rut {
                (draw.range(0.020, 0.042), params.disturbance_depth_m * 0.85, 0.40)
            } else if roll < 0.78 {
                // Voids and collapses between aggregates. No rim: a pore is
                // where material is absent, not where it was thrown. Ringing
                // every one of them was the other half of the speckle.
                (draw.range(0.010, 0.028), params.disturbance_depth_m * 0.60, 0.0)
            } else if roll < 0.97 {
                // Something stood here. These do throw a rim.
                (draw.range(0.028, 0.060), params.disturbance_depth_m * 1.0, 0.55)
            } else {
                // Broad pressed patches, kept shallow. At any real depth these
                // stop being where something stood and become craters.
                (draw.range(0.060, 0.13), params.disturbance_depth_m * 0.40, 0.30)
            };

            // Elliptical and turned, and a shared bias in the turn so that a
            // stretch of ground looks worked over rather than randomly pocked.
            let bias = fbm(seed ^ 0x0D15_7B00, Stream::Flow, at.x * 0.7, at.y * 0.7, 2);
            // A rut holds the travel line; a pit only leans toward it. That
            // difference in *jitter* is what makes a set of ruts read as one
            // direction and a set of pits read as scatter.
            let wander = if is_rut { 0.12 } else { 0.5 };
            let angle = bias * std::f32::consts::TAU + draw.range(-wander, wander);
            let (sin, cos) = angle.sin_cos();
            let squash = if is_rut {
                draw.range(6.0, 14.0)
            } else {
                draw.range(1.0, 2.1)
            };
            let warp = draw.range(0.15, 0.45);

            let footprint = move |world: Vec2| -> f32 {
                let d = world - at;
                let along = (d.x * cos + d.y * sin) / squash;
                let across = -d.x * sin + d.y * cos;
                let r = (along * along + across * across).sqrt() / radius;
                // An irregular edge, so the outline is not an ellipse.
                let wobble = 1.0 + warp * (3.0 * across.atan2(along)).sin();
                (r / wobble.max(0.2)).min(4.0)
            };

            // Take material out of the middle...
            // Scanned unclipped, for the reason written out in `splat`: a rim
            // normalised over only the cells inside the grid depends on where
            // the grid ends, and a pit at a tile boundary would throw up a
            // heavier rim than the same pit in the middle.
            let mut removed = 0.0;
            let mut inside: Vec<usize> = Vec::new();
            let reach = (radius * squash * 2.6 / grid.cell_m).ceil() as i32;
            let centre = grid.cell_of(at);
            let (cx, cy) = (centre.x.round() as i32, centre.y.round() as i32);
            let width = grid.width as i32;
            let rim_share = rim;
            let mut rim: Vec<(usize, f32)> = Vec::new();
            let mut rim_total = 0.0;
            // The cut has to be totalled unclipped too, or a pit half outside
            // returns a full pit's worth of spoil to half a rim.
            let mut nominal = 0.0;

            for y in (cy - reach)..=(cy + reach) {
                for x in (cx - reach)..=(cx + reach) {
                    let held = x >= 0 && y >= 0 && x < width && y < width;
                    let r = footprint(grid.world_of_unclamped(x, y));
                    if r < 1.0 {
                        let cut = depth * (1.0 - r * r) * (1.0 - r * r);
                        nominal += cut;
                        if held {
                            let index = grid.at(x as usize, y as usize);
                            let cut = cut.min(grid.soil[index]);
                            grid.soil[index] -= cut;
                            removed += cut;
                            inside.push(index);
                        }
                    } else if r < 1.9 {
                        // ...and pile it just outside, in a ring.
                        let t = (r - 1.0) / 0.9;
                        let weight = (1.0 - t) * t * 4.0;
                        if weight > 0.0 {
                            rim_total += weight;
                            if held {
                                rim.push((grid.at(x as usize, y as usize), weight));
                            }
                        }
                    }
                }
            }
            let _ = removed;
            let removed = nominal;

            if rim_total > 0.0 && rim_share > 0.0 {
                // Not all of it: some is carried away, and a print that returns
                // every gram to its own rim reads as a stamped ring.
                let returned = removed * rim_share;
                for (index, weight) in rim {
                    grid.soil[index] += returned * weight / rim_total;
                }
            }
            // What is left in the hollow has been pressed, and pressed soil
            // holds. This is why old prints keep their shape.
            // A rut's floor is pressed harder than a footprint's: it has been
            // run over repeatedly along the same line, which is what turns loose
            // material into a coherent compacted plane rather than a dent.
            let press = if is_rut { 0.80 } else { 0.45 };
            for index in inside {
                grid.strength[index] = (grid.strength[index] + press).min(1.0);
            }
        },
    );
}

/// Stage four: short downhill paths that lift loose material and drop it low.
///
/// Not an erosion simulation — a few tens of cells each, and weak. What it is
/// for is *direction*. Everything above it is isotropic, and isotropy is the
/// other half of what reads as procedural: real ground has a downhill, and the
/// loose material on it has been moved that way. A faint organisation along one
/// axis is worth more here than any amount of extra relief.
fn wash(grid: &mut Grid, params: &Params, seed: u64) {
    if params.wash_strength <= 0.0 {
        return;
    }
    let inv = 1.0 / grid.cell_m;
    // ## No margin, unlike the stages above it
    //
    // A packet or a pit centred outside the grid still reaches cells inside it,
    // so those must be generated beyond the edge. A wash path is different: it
    // *starts* where it starts and walks from there, and the walk stops dead at
    // the grid boundary because there is no gradient to read outside it.
    //
    // Generating paths outside the grid therefore does not extend their reach —
    // it just creates paths that immediately halt. Which would be harmless
    // except that a wider grid halts them later, so the interior came to depend
    // on the halo width: doubling it moved cells by three quarters of a
    // millimetre. The halo is what covers this case, and it covers it properly —
    // a path beginning at the halo's outer edge can reach `WASH_STEPS` cells
    // inward and still stop half a halo short of the interior.
    for_each_event(grid, seed, Stream::Flow, params.wash_per_m2, 0.0, 0.30, |draw, at, grid| {
        let mut draw = draw;
        let mut position = grid.cell_of(at);
        let mut carried = 0.0;
        let mut heading = Vec2::ZERO;

        for _ in 0..WASH_STEPS {
            let (x, y) = (position.x.round() as i32, position.y.round() as i32);
            if x < 1 || y < 1 || x >= grid.width as i32 - 1 || y >= grid.width as i32 - 1 {
                break;
            }
            let (x, y) = (x as usize, y as usize);
            let here = grid.at(x, y);

            let gradient = Vec2::new(
                grid.soil[grid.at(x + 1, y)] - grid.soil[grid.at(x - 1, y)],
                grid.soil[grid.at(x, y + 1)] - grid.soil[grid.at(x, y - 1)],
            ) * (0.5 * inv);

            // Persistence, so a path runs rather than jittering into the
            // nearest hole. A jittering path deposits in a dot; a running one
            // leaves the streak this stage exists for.
            heading = (heading * 0.55 - gradient).normalize_or_zero();
            if heading == Vec2::ZERO {
                heading = Vec2::new(draw.signed(), draw.signed()).normalize_or_zero();
            }

            let steepness = gradient.length();
            let capacity = params.wash_strength * steepness * grid.cell_m;
            if carried < capacity {
                // Only what is loose. Packed ground and strong aggregates stay,
                // which is what leaves a clean ridge beside a scoured hollow.
                let available = grid.soil[here] * (1.0 - grid.strength[here]) * 0.05;
                let lifted = available.min((capacity - carried) * 0.5);
                grid.soil[here] -= lifted;
                carried += lifted;
            } else {
                let dropped = (carried - capacity) * 0.4;
                grid.soil[here] += dropped;
                carried -= dropped;
            }

            position += heading;
        }

        // Whatever is still carried is put down where it stopped, so the stage
        // conserves material rather than quietly removing it.
        let (x, y) = (position.x.round() as i32, position.y.round() as i32);
        if x >= 0 && y >= 0 && x < grid.width as i32 && y < grid.width as i32 {
            let index = grid.at(x as usize, y as usize);
            grid.soil[index] += carried;
        }
    });
}

/// How heavily worked this patch of ground is, `0..1`, on a slow world field.
///
/// ## The events had a history and their density did not
///
/// Simulating the events instead of describing their outcome fixed the shaping,
/// and left a subtler version of the same defect standing: the events were laid
/// down at a *constant rate*, so every square hand's-width of ground received
/// the same number of packets and the same number of pits. The surface therefore
/// still had one statistic everywhere — evenly churned, evenly pitted — which is
/// what "reads as churned crust rather than settled earth" describes.
///
/// Real ground is worked in patches. Something walked here and not there; this
/// corner has been rained on and swept smooth; that one was turned last week and
/// still stands in lumps. So the rate itself varies, slowly, and quiet stretches
/// sit against broken ones.
///
/// Deliberately much slower than the events it gates — metres, not centimetres —
/// because at any shorter scale it stops reading as *where things happened* and
/// becomes another texture.
fn worked(seed: u64, world: Vec2, floor: f32) -> f32 {
    // ## Larger patches and a harder edge between them
    //
    // This ran at 0.55 — patches under two metres — through a soft ramp, and the
    // render still came back described as "a fairly uniform procedural stipple
    // across the bare expanse". Both numbers were the reason. Patches that small
    // average out inside any crop a viewer looks at, so the variation exists in
    // the field and not in the picture; and a soft ramp spends most of its range
    // in the middle, so almost everywhere is *moderately* worked and nowhere is
    // plainly one thing or the other.
    //
    // Real ground organises into large irregular regions with recognisable edges
    // — this stretch was churned, that one was left, the corner has been swept
    // smooth by runoff. Three and a half metres puts a region at half a plate,
    // and the steeper ramp makes most of the ground commit to one state or the
    // other with a readable transition between.
    let raw = fbm(
        seed ^ 0x_B_0_1_5_E,
        Stream::Maturity,
        world.x * 0.28,
        world.y * 0.28,
        2,
    );
    floor + (1.0 - floor) * smoothstep(0.40, 0.62, raw)
}

/// Visit every event whose influence can reach this grid, seeded from the world.
///
/// The seam guarantee, in one function. Events are generated per coarse *world*
/// cell rather than per tile, so a packet lying across a tile boundary is drawn
/// identically by both tiles that can see it — same position, same size, same
/// lobes. Nothing is taken from a running sequence, because a running sequence
/// depends on how many draws preceded it and therefore on where the window
/// began.
fn for_each_event(
    grid: &mut Grid,
    seed: u64,
    stream: Stream,
    per_m2: f32,
    margin_m: f32,
    worked_floor: f32,
    mut place: impl FnMut(Draw, Vec2, &mut Grid),
) {
    // The margin is how far this kind of event reaches from where it starts. A
    // packet reaches its own radius; a wash path reaches `WASH_STEPS` cells and
    // is the reason this parameter exists at all — paths beginning just outside
    // the grid still cross it, and leaving them ungenerated made a tile's answer
    // depend on its halo width, which is the one thing the halo must not do.
    let span = grid.width as f32 * grid.cell_m;
    let corner = grid.world_of_unclamped(0, 0);
    let low = corner - Vec2::splat(grid.cell_m + margin_m);
    let high = corner + Vec2::splat(span + grid.cell_m + margin_m);
    let per_cell = per_m2 * EVENT_CELL_M * EVENT_CELL_M;

    let x0 = (low.x / EVENT_CELL_M).floor() as i32;
    let y0 = (low.y / EVENT_CELL_M).floor() as i32;
    let x1 = (high.x / EVENT_CELL_M).ceil() as i32;
    let y1 = (high.y / EVENT_CELL_M).ceil() as i32;

    for cell_y in y0..=y1 {
        for cell_x in x0..=x1 {
            let mut draw = Draw::at(seed, stream, cell_x, cell_y);
            // A whole number of events plus a fractional chance of one more, so
            // a density below one per cell still means something.
            // Gated by how worked this patch is, so the ground has quiet
            // stretches beside broken ones instead of one statistic everywhere.
            let here = per_cell
                * worked(
                    seed,
                    Vec2::new(
                        (cell_x as f32 + 0.5) * EVENT_CELL_M,
                        (cell_y as f32 + 0.5) * EVENT_CELL_M,
                    ),
                    worked_floor,
                );
            let whole = here.floor() as usize;
            let count = whole + usize::from(draw.unit() < here - whole as f32);
            for _ in 0..count.min(64) {
                let at = Vec2::new(
                    (cell_x as f32 + draw.unit()) * EVENT_CELL_M,
                    (cell_y as f32 + draw.unit()) * EVENT_CELL_M,
                );
                place(draw, at, grid);
                // Advance so the next event in this cell differs, while staying
                // a pure function of the cell.
                draw.unit();
            }
        }
    }
}

/// One landform band, as the bed the simulation runs over.
///
/// The same two turned copies of one frequency that `ground::band_height` uses,
/// for the same reason written out there: a single octave of value noise shows
/// its own lattice as quilting, and more octaves would put content at scales the
/// events already own. Unshaped, because a swell is a swell — the shaping
/// vocabulary describes aggregates, and this is the ground under them.
fn broad_band(
    band: &terrain_core::ground_material::ReliefBand,
    index: usize,
    world: Vec2,
    seed: u64,
) -> f32 {
    let frequency = 1.0 / band.wavelength_m.max(1.0e-4);
    let seed = seed ^ (0x9E37_79B9_u64.wrapping_mul(index as u64 + 1));
    let mut sum = 0.0;
    for turn in 0..2 {
        let angle = 2.399_963_2 * (index as f32 * 2.0 + turn as f32 + 1.0);
        let (sin, cos) = angle.sin_cos();
        let offset = 37.0 * (index * 2 + turn) as f32;
        let x = (world.x * cos - world.y * sin) * frequency + offset;
        let y = (world.x * sin + world.y * cos) * frequency - offset;
        sum += crate::rng::value_noise(seed, Stream::GroundRelief, x, y);
    }
    ((sum * 0.5 - 0.5) * 1.41) * band.amplitude_m
}

#[inline]
fn smoothstep(edge0: f32, edge1: f32, value: f32) -> f32 {
    if edge1 <= edge0 {
        return f32::from(value >= edge1);
    }
    let t = ((value - edge0) / (edge1 - edge0)).clamp(0.0, 1.0);
    t * t * (3.0 - 2.0 * t)
}

#[cfg(test)]
mod tests {
    use super::*;
    use terrain_core::ground_material::{
        AggregateShape, GroundOptics, GroundScatter, GroundStructure, ReliefBand, Span, WetResponse,
    };
    use terrain_core::ids::{AppearanceKey, GroundProfileKey};

    fn loam() -> Arc<GroundMaterialProfile> {
        Arc::new(GroundMaterialProfile {
            key: GroundProfileKey::new("test_loam").expect("key"),
            display_name: "Test loam".into(),
            shader: AppearanceKey::new("ground").expect("key"),
            optics: GroundOptics {
                dry_palette: terrain_core::ground_material::Palette {
                    low: [0.01, 0.008, 0.004],
                    mid: [0.04, 0.026, 0.014],
                    high: [0.13, 0.083, 0.046],
                },
                wet: WetResponse {
                    wet_mid: [0.018, 0.011, 0.005],
                    roughness_wet: 0.3,
                    saturation_flattening: 0.42,
                    film_ior: 1.333,
                },
                roughness_dry: Span::new(0.82, 0.96),
                ior: 1.48,
                region_wavelength_m: 2.0,
                region_strength: 0.3,
                patch_wavelength_m: 0.22,
                patch_strength: 0.34,
                grain_strength: 0.55,
            },
            structure: GroundStructure {
                bands: vec![
                    ReliefBand {
                        wavelength_m: 0.15,
                        amplitude_m: 0.028,
                        shape: AggregateShape::Rounded,
                        compaction_response: 0.30,
                        clustered: false,
                    },
                    ReliefBand {
                        wavelength_m: 0.06,
                        amplitude_m: 0.028,
                        shape: AggregateShape::RoundedRidged,
                        compaction_response: 0.30,
                        clustered: true,
                    },
                ],
                cluster_wavelength_m: 0.8,
                cluster_strength: 0.5,
                cohesion: 0.62,
                mesh_floor_m: Some(0.016),
            },
            ripples: None,
            cracks: None,
            scatter: GroundScatter {
                grit_per_m2: 90.0,
                pebble_per_m2: 0.5,
                fragment_radius_m: Span::new(0.004, 0.02),
            },
            vegetation_affinity: 0.0,
        })
    }

    #[test]
    fn a_tile_is_a_pure_function_of_where_it_is() {
        // Two surfaces built independently must agree everywhere, or a plate
        // traced in slices grows seams down the joins between them.
        let a = SoilSurface::new(loam(), 0x51_11);
        let b = SoilSurface::new(loam(), 0x51_11);
        for i in 0..40 {
            let p = Vec2::new(i as f32 * 0.137 - 2.0, i as f32 * -0.211 + 1.3);
            let (x, y) = (a.height(p, 0.4, 0.6), b.height(p, 0.4, 0.6));
            assert_eq!(x, y, "at {p:?}");
        }
    }

    #[test]
    fn the_halo_is_wide_enough_that_the_interior_has_settled() {
        // The claim `HALO_CELLS` rests on: transport into a tile's interior dies
        // out well before the halo's edge, so a wider halo changes nothing. If
        // this fails the halo is too narrow and tiles disagree at their joins —
        // which is the one failure this whole tiling scheme has to avoid.
        let surface = SoilSurface::new(loam(), 0xA11_0);
        let narrow = surface.simulate((0, 0), 0.4, 0.6, HALO_CELLS);
        let wide = surface.simulate((0, 0), 0.4, 0.6, HALO_CELLS * 2);
        let differences: Vec<f32> = narrow
            .height
            .iter()
            .zip(&wide.height)
            .map(|(a, b)| (a - b).abs())
            .collect();
        let moved = differences.iter().filter(|d| **d > 0.0).count();
        let worst = differences.iter().copied().fold(0.0f32, f32::max);

        // ## Almost every cell is bit-identical, and a couple are not
        //
        // Coordinates are anchored to the tile rather than to the grid, so the
        // same world point is computed by the same sum whatever the halo — see
        // `Grid::origin`. That makes the great majority of the interior agree
        // exactly rather than merely closely.
        //
        // A handful of cells still differ, and the reason is inherent rather
        // than fixable. The slump has a *threshold* in it: material moves or it
        // does not. A cell sitting within a hair of that threshold can be tipped
        // either way by the last-place difference in a neighbour arriving from
        // further out, and a hundred and eighty passes then amplify the choice.
        // Two cells in sixty-three thousand, by under a millimetre, on relief
        // measured in centimetres.
        //
        // What this test therefore claims is that the halo is wide enough for
        // the interior to have settled, not that a chaotic iteration is
        // reproducible across two different amounts of surrounding ground. The
        // guarantee that tiles agree *with each other* is the next test, and it
        // is the one seams actually depend on.
        assert!(
            moved * 200 < differences.len(),
            "{moved} of {} cells moved when the halo doubled",
            differences.len()
        );
        assert!(worst < 1.5e-3, "doubling the halo moved a cell by {worst} m");
    }

    #[test]
    fn neighbouring_tiles_agree_across_their_join() {
        // The same test from the sampling side. A point just inside one tile and
        // a point just inside the next must describe one continuous surface.
        // Sampled densely along a whole join, and across both axes, because a
        // seam is a line rather than a point and one bad cell on it is a visible
        // crack running the height of a plate.
        let surface = SoilSurface::new(loam(), 0x_10_1D);
        let mut worst = 0.0f32;
        for i in 0..500 {
            let t = -1.0 + i as f32 * 0.004;
            for (a, b) in [
                (
                    Vec2::new(TILE_M - 1.0e-4, t),
                    Vec2::new(TILE_M + 1.0e-4, t),
                ),
                (
                    Vec2::new(t, TILE_M - 1.0e-4),
                    Vec2::new(t, TILE_M + 1.0e-4),
                ),
            ] {
                let step = (surface.height(a, 0.4, 0.6) - surface.height(b, 0.4, 0.6)).abs();
                worst = worst.max(step);
            }
        }
        // ## What this bounds, and what it does not
        //
        // Measured at half a millimetre over a thousand samples of two full
        // joins, against centimetres of relief either side. A traced pixel at
        // this project's resolution is 3.1 mm, so the seam is a sixth of one and
        // cannot be resolved even in principle.
        //
        // It is not zero, and chasing it to zero would be chasing the wrong
        // thing. The slump has a threshold in it and two tiles see different
        // ground beyond their halos, so a cell sitting within a hair of that
        // threshold can fall either way — see the previous test. The figure also
        // rises as the surface gains variation, which is why it moved from a
        // third of a millimetre to a half when the events started varying in
        // density: more relief, more cells near the threshold.
        //
        // What this test is for is *structural* seams. It is the test that
        // caught tiles storing one sample too few, which put a cell-wide gap
        // between neighbours and stepped the join by **seventeen millimetres** —
        // thirty times this bound, and plainly visible as a crack running the
        // height of a plate.
        assert!(worst < 1.0e-3, "the join steps by {worst} m");
    }

    #[test]
    fn the_surface_is_not_the_same_everywhere() {
        // The defect this module exists for. Procedural noise is statistically
        // uniform: every patch has the same distribution as every other, which
        // is why a metre of it reads as one texture tiled. A surface with a
        // history does not — some of it was worked over, some was left alone.
        //
        // Measured as the spread of per-patch roughness across a plate. A noise
        // field's is near zero by construction.
        let surface = SoilSurface::new(loam(), 0x5EED);
        let mut patches = Vec::new();
        for py in 0..4 {
            for px in 0..4 {
                let mut values = Vec::new();
                for i in 0..24 {
                    for j in 0..24 {
                        values.push(surface.height(
                            Vec2::new(
                                px as f32 * 0.25 + i as f32 * 0.01,
                                py as f32 * 0.25 + j as f32 * 0.01,
                            ),
                            0.4,
                            0.6,
                        ));
                    }
                }
                let mean = values.iter().sum::<f32>() / values.len() as f32;
                let variance = values.iter().map(|v| (v - mean).powi(2)).sum::<f32>()
                    / values.len() as f32;
                patches.push(variance.sqrt());
            }
        }
        let mean = patches.iter().sum::<f32>() / patches.len() as f32;
        let spread = patches
            .iter()
            .map(|p| (p - mean).abs())
            .fold(0.0f32, f32::max);
        assert!(
            spread / mean > 0.25,
            "every patch has the same roughness ({mean:.5} +/- {spread:.5}); \
             the surface is statistically uniform and will read as tiled noise"
        );
    }

    #[test]
    fn the_ground_can_shadow_itself() {
        // The sun is at 35 degrees, so a face has to tilt past 35 before it
        // falls into its own shadow. A noise-based surface never did, at any
        // moisture, anywhere — which is why every apparent feature on it was
        // pigment rather than form.
        let surface = SoilSurface::new(loam(), 0x_5AD5);
        let step = 0.004;
        let mut steep = 0;
        let mut total = 0;
        for i in 0..200 {
            for j in 0..200 {
                let p = Vec2::new(i as f32 * step, j as f32 * step);
                let h = surface.height(p, 0.4, 0.6);
                let dx = (surface.height(p + Vec2::new(step, 0.0), 0.4, 0.6) - h) / step;
                let dy = (surface.height(p + Vec2::new(0.0, step), 0.4, 0.6) - h) / step;
                total += 1;
                if dx.hypot(dy) > 35.0f32.to_radians().tan() {
                    steep += 1;
                }
            }
        }
        let share = steep as f32 / total as f32;
        assert!(
            share > 0.02,
            "only {:.2}% of the surface can shadow at a 35-degree sun",
            share * 100.0
        );
    }
}
